version: "3"
services:
    database:
        image: "mysql:8.0"
        container_name: "gestione-pianificazione-db"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USERNAME: root
            MYSQL_DATABASE: gestionepianificazione

    keycloak:
        image: quay.io/keycloak/keycloak:17.0.0
        container_name: keycloak
        ports:
            - '8082:8080'
        environment:
            KEYCLOAK_ADMIN_PASSWORD: admin
            KEYCLOAK_ADMIN: admin


